# Generated by Django 2.2 on 2020-09-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizardform',
            name='file',
        ),
        migrations.RemoveField(
            model_name='wizardform',
            name='firstFile',
        ),
        migrations.RemoveField(
            model_name='wizardform',
            name='secondFile',
        ),
        migrations.RemoveField(
            model_name='wizardform',
            name='uploader',
        ),
    ]
