# Generated by Django 2.2 on 2020-09-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardform',
            name='mobile_phone_fin',
            field=models.IntegerField(null=True),
        ),
    ]
