# Generated by Django 2.2 on 2020-10-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardform',
            name='email_fin',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wizardform',
            name='email_info',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
    ]
