# Generated by Django 2.1.3 on 2020-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step1FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('bemovil_id', models.IntegerField()),
                ('personal_id', models.TextField(max_length=100)),
                ('expedition_date', models.DateField()),
                ('expedition_place', models.CharField(max_length=100)),
                ('mobile_phone', models.IntegerField()),
                ('number', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('valley', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Step2FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('valley', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Step3FormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_phone', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
