# Generated by Django 2.2 on 2020-09-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_wizardform_mobile_phone_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardform',
            name='email_fin',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
    ]
