# Generated by Django 2.2 on 2020-09-22 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_wizardform_email_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizardform',
            name='is_confirmed',
        ),
    ]
