# Generated by Django 2.1.3 on 2020-09-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200903_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step1formmodel',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='bemovil_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='expedition_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='expedition_place',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='mobile_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='personal_id',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='valley',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step2formmodel',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step2formmodel',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step2formmodel',
            name='valley',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='step3formmodel',
            name='mobile_phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='step3formmodel',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
