# Generated by Django 2.2 on 2020-10-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20201005_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardformnatural',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
