# Generated by Django 2.1.3 on 2020-09-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200903_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpictures',
            name='image',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
