# Generated by Django 2.2 on 2020-10-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wizardformnatural_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='id_image1',
            field=models.FileField(null=True, upload_to='user_images/id_images'),
        ),
    ]
