# Generated by Django 2.2 on 2020-09-24 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_phonemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneOTP',
        ),
    ]
