# Generated by Django 2.1.3 on 2020-09-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200903_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpictures',
            name='user_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
