# Generated by Django 2.2 on 2020-09-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizardform',
            name='email_info',
            field=models.EmailField(default='', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wizardform',
            name='lastname_info',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wizardform',
            name='name_info',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='wizardform',
            name='number_info',
            field=models.IntegerField(null=True),
        ),
    ]
