# Generated by Django 2.1.3 on 2020-09-04 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200903_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpictures',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpictures',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
