# Generated by Django 2.2 on 2020-10-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201006_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='url',
        ),
        migrations.AddField(
            model_name='email',
            name='final_pdf',
            field=models.FileField(default='', upload_to='documents'),
        ),
    ]
