# Generated by Django 2.1.3 on 2020-09-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_userpictures_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpictures',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userpictures',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='userpictures',
            name='image2',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
        migrations.AddField(
            model_name='userpictures',
            name='image3',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
