# Generated by Django 2.2 on 2020-10-22 19:47

from django.db import migrations, models
import multi_step_form.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='client_image1',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='client_image2',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='client_image3',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='firstFile',
            field=models.FileField(blank=True, null=True, upload_to='documents', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='id_image1',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/id_images', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='id_image2',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/id_images', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='secondFile',
            field=models.FileField(blank=True, null=True, upload_to='documents', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='client_image1',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='client_image2',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='client_image3',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='firstFile',
            field=models.FileField(blank=True, null=True, upload_to='documents', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='id_image1',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/id_images', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='id_image2',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/id_images', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='secondFile',
            field=models.FileField(blank=True, null=True, upload_to='documents', validators=[multi_step_form.validators.validate_file_extension]),
        ),
    ]
