# Generated by Django 2.1.3 on 2020-09-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200906_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardFormModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('bemovil_id', models.IntegerField(null=True)),
                ('personal_id', models.TextField(max_length=100, null=True)),
                ('expedition_date', models.DateField(null=True)),
                ('expedition_place', models.CharField(max_length=100, null=True)),
                ('mobile_phone', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('valley', models.CharField(max_length=100, null=True)),
                ('image1', models.ImageField(null=True, upload_to='user_images/')),
                ('image2', models.ImageField(null=True, upload_to='user_images/')),
                ('image3', models.ImageField(null=True, upload_to='user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Step1FormModel',
        ),
        migrations.DeleteModel(
            name='Step2FormModel',
        ),
        migrations.DeleteModel(
            name='Step3FormModel',
        ),
        migrations.DeleteModel(
            name='UserPictures',
        ),
    ]
