# Generated by Django 2.2 on 2020-10-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201022_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='number',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
