# Generated by Django 2.1.3 on 2020-09-09 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200907_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
