# Generated by Django 2.1.3 on 2020-09-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200909_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader', models.CharField(max_length=20)),
                ('firstFile', models.FileField(upload_to='documents')),
                ('secondFile', models.FileField(upload_to='documents')),
                ('file', models.BinaryField(null=True)),
            ],
        ),
    ]
