# Generated by Django 2.2 on 2020-10-24 16:21

from django.db import migrations, models
import multi_step_form.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201024_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='ciudad',
            new_name='ciudad_partiner',
        ),
        migrations.RemoveField(
            model_name='wizardformjuridica',
            name='telefono_fijo',
        ),
        migrations.RemoveField(
            model_name='wizardformnatural',
            name='telefono_fijo',
        ),
        migrations.AlterField(
            model_name='partner',
            name='participacion',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='counter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='bemovil_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='client_image1',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='client_image2',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='client_image3',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='egresos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='id_image1',
            field=models.ImageField(null=True, upload_to='user_images/id_images'),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='id_image2',
            field=models.ImageField(null=True, upload_to='user_images/id_images'),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='ingresos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='mobile_phone',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='mobile_phone_fin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='number_info',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='total_activos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformjuridica',
            name='total_pasivos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='bemovil_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='client_image1',
            field=models.ImageField(null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='client_image2',
            field=models.ImageField(null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='client_image3',
            field=models.ImageField(null=True, upload_to='user_images/', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='egresos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='id_image1',
            field=models.ImageField(null=True, upload_to='user_images/id_images', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='id_image2',
            field=models.ImageField(null=True, upload_to='user_images/id_images', validators=[multi_step_form.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='ingresos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='mobile_phone',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='mobile_phone_fin',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='number_info',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='total_activos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='wizardformnatural',
            name='total_pasivos',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
