# Generated by Django 2.1.3 on 2020-09-11 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step1formmodel',
            name='client_id',
        ),
        migrations.AddField(
            model_name='filemodel',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Step1FormModel'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Step1FormModel'),
        ),
        migrations.AddField(
            model_name='step2formmodel',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Step1FormModel'),
        ),
        migrations.AddField(
            model_name='step3formmodel',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Step1FormModel'),
        ),
        migrations.AddField(
            model_name='userpictures',
            name='client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Step1FormModel'),
        ),
        migrations.AlterField(
            model_name='step1formmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
