# Generated by Django 2.1.3 on 2020-09-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200911_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='step2formmodel',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='step3formmodel',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='userpictures',
            name='client_id',
        ),
    ]
