# Generated by Django 2.2 on 2020-09-14 22:30

from django.db import migrations, models
import multiselectfield.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200912_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='WizardForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('_type', models.CharField(choices=[(1, 'Natural'), (2, 'Juridica')], max_length=100)),
                ('personal_id', models.TextField(max_length=250, null=True)),
                ('firstname', models.CharField(max_length=250, null=True)),
                ('lastname', models.CharField(max_length=250, null=True)),
                ('bemovil_id', models.IntegerField(null=True)),
                ('expedition_date', models.DateField(null=True)),
                ('expedition_place', models.CharField(max_length=250, null=True)),
                ('mobile_phone', models.IntegerField(null=True)),
                ('number', models.IntegerField(null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('address', models.TextField(max_length=250, null=True)),
                ('city', models.CharField(max_length=250, null=True)),
                ('valley', models.CharField(max_length=250, null=True)),
                ('company_name', models.CharField(max_length=250, null=True)),
                ('actividad_economica', models.CharField(max_length=250, null=True)),
                ('direccion', models.TextField(max_length=250, null=True)),
                ('barrio', models.CharField(max_length=250, null=True)),
                ('ciudad', models.CharField(max_length=250, null=True)),
                ('departamento', models.CharField(max_length=250, null=True)),
                ('telefono_fijo', models.IntegerField(blank=True, null=True)),
                ('ingresos', models.IntegerField(blank=True, null=True)),
                ('total_activos', models.IntegerField(blank=True, null=True)),
                ('egresos', models.IntegerField(blank=True, null=True)),
                ('total_pasivos', models.IntegerField(blank=True, null=True)),
                ('name_razonsocial', models.TextField(max_length=250, null=True)),
                ('participacion', models.IntegerField(max_length=250, null=True)),
                ('identification', models.CharField(max_length=250, null=True)),
                ('terms', multiselectfield.db.fields.MultiSelectField(choices=[('term_key1', 'Terminos y condicions'), ('term_key2', 'Autorizacion para consulta y reporte'), ('term_key3', 'Tratamiento de datos personales'), ('term_key4', 'Autorizacion para el Tratamiento de datos personales'), ('term_key5', 'origen de fondos')], max_length=49)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('firstFile', models.FileField(upload_to='documents')),
                ('secondFile', models.FileField(upload_to='documents')),
                ('file', models.BinaryField(null=True)),
                ('id_image1', models.ImageField(null=True, upload_to='user_images/id_images')),
                ('id_image2', models.ImageField(null=True, upload_to='user_images/id_images')),
                ('client_image1', models.ImageField(null=True, upload_to='user_images/')),
                ('client_image2', models.ImageField(null=True, upload_to='user_images/')),
                ('client_image3', models.ImageField(null=True, upload_to='user_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FileModel',
        ),
        migrations.DeleteModel(
            name='Step1FormModel',
        ),
        migrations.DeleteModel(
            name='Step2FormModel',
        ),
        migrations.DeleteModel(
            name='Step3FormModel',
        ),
        migrations.DeleteModel(
            name='UserPictures',
        ),
    ]
