# Generated by Django 2.2 on 2020-09-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200915_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizardform',
            name='participacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wizardform',
            name='terms',
            field=models.BooleanField(choices=[('term_key1', 'Terminos y condicions'), ('term_key2', 'Autorizacion para consulta y reporte'), ('term_key3', 'Tratamiento de datos personales'), ('term_key4', 'Autorizacion para el Tratamiento de datos personales'), ('term_key5', 'origen de fondos')]),
        ),
    ]
