# Generated by Django 2.2 on 2020-09-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200915_0059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wizardform',
            name='terms',
        ),
        migrations.AddField(
            model_name='wizardform',
            name='term1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wizardform',
            name='term2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wizardform',
            name='term3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wizardform',
            name='term4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wizardform',
            name='term5',
            field=models.BooleanField(default=False),
        ),
    ]
